# Generated by Django 4.2.1 on 2023-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('mobile', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
