# Generated by Django 4.2.1 on 2023-07-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
